name = "verifynfc"
main = "worker/index.js"
compatibility_date = "2024-10-31"
workers_dev = true
# logpush disabled for non-Enterprise accounts
# logpush = false
compatibility_flags = ["nodejs_compat"]

# Custom domain route
routes = [
  { pattern = "verify.plearance.com/*", zone_name = "plearance.com" }
]

[vars]
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "admin123"
ADMIN_TOKEN_TTL_HOURS = "24"

[assets]
directory = "./public"

# Configure D1 (set your real database_id after creating D1 in Cloudflare)
[[d1_databases]]
binding = "DB"
database_name = "nfc-verification-worker"
database_id = "eabca273-1f85-416a-b1c7-b59dda3ab658"

# Migrations directory for D1
migrations_dir = "migrations"